### ISSUE TITLE
Image smaller, game slower then on the demo

### ISSUE THREAD

**Issue by andreykuzovlevv** [eloialonso/diamond#13]
## Is there anything to get it better?

https://github.com/user-attachments/assets/3903d013-c3ac-4fb0-beae-1f42bf8feea8

**Comment by eloialonso** [comment]
You can use the `--size-multiplier` argument (we used 5 in the demo).

For the speed, we recommend using a GPU if you can, and adding the `--compile` flag. For the demo, we used an RTX 3090. It looks like some people got fast generation with M3 chips too.

You can also change the sampling parameters to use less sampling steps, but this will reduce the visual quality.

**Comment by Willian7004** [comment]
You can try switching the scaling to 100% if you are using Linux with X11.
