### ISSUE TITLE
great research, how can i train on my own dataset? what do i need to prepare? thank you very much

### ISSUE THREAD

**Issue by D-Mad** [eloialonso/diamond#15]

**Comment by TeaPearce** [comment]
fundamentally, you just need a dataset of video/images (game frames) and actions taken between each frame (eg controller or keyboard)

**Comment by eloialonso** [comment]
You can provide your own dataset in the [static_dataset.path](https://github.com/eloialonso/diamond/blob/312a0c4ef386bc031b8bdc1f2928100e7a2ef482/config/trainer.yaml#L50) argument of the configuration file.

This is supposed to be a folder with two subfolders, `train` and `test`, each formatted as a `Dataset` from the [dataset.py](https://github.com/eloialonso/diamond/blob/main/src/data/dataset.py) file.
