### ISSUE TITLE
would it be possible to use pyinstaller to make it more userfriendly? 

### ISSUE THREAD

**Issue by thespecificjhevin** [eloialonso/diamond#17]
im no pc genius , far from it, i would just like to try it out but im no pc wiz so id like a easy way to play it, a nice download of a zip or a tar.gz would be nice, if its not possible thats cool too

**Comment by eloialonso** [comment]
Hey, thanks for the interest! 

Unfortunately, we are not planning to release a zip or to support pyinstaller for now.

You might find [this video](https://www.youtube.com/watch?v=6Md5U8rMZjI&t=315s) helpful, as the person covers the installation process (on Ubuntu). 

Also, as mentioned in #9, if you want to play on an Nvidia GPU, you have to make sure that you have a cuda-enabled installation of PyTorch.
