### ISSUE TITLE
this is AWESOME 🎉🎉🎉

### ISSUE THREAD

**Issue by johnpaulbin** [eloialonso/diamond#18]
AWESOME WORK!!!! :DDD

This is genuinely one of the most interesting research projects done in a WHILE, and DOUBLE THANKS for keeping it open source!!!!

**Comment by eloialonso** [comment]
Thank you for the kind words!!

We're really pleased that the community is finding our work interesting and useful, and is enjoying playing our world models as much as we do :)

Eloi & Adam
