### ISSUE TITLE
The training data set confuses me, how to build it? 

### ISSUE THREAD

**Issue by win10ogod** [eloialonso/diamond#19]
The training data set confuses me, how to build it?
how can i train on my own dataset? what do i need to prepare?

**Comment by AdamJelley** [comment]
We describe the training dataset we used and how to prepare it [in the README](https://github.com/eloialonso/diamond/tree/csgo?tab=readme-ov-file#data). We also provide the training code, which you can run with `python src/main.py`, provided that you have the data downloaded and prepared on your machine. 

For training on your own dataset, you need to provide your own dataset in the [static_dataset.path](https://github.com/eloialonso/diamond/blob/312a0c4ef386bc031b8bdc1f2928100e7a2ef482/config/trainer.yaml#L50) argument of the configuration file. This should be a folder with two subfolders, `train` and `test`, each formatted as a `Dataset` from the [dataset.py](https://github.com/eloialonso/diamond/blob/main/src/data/dataset.py) file.

**Comment by win10ogod** [comment]
> We describe the training dataset we used and how to prepare it [in the README](https://github.com/eloialonso/diamond/tree/csgo?tab=readme-ov-file#data). We also provide the training code, which you can run with `python src/main.py`, provided that you have the data downloaded and prepared on your machine.
> 
> For training on your own dataset, you need to provide your own dataset in the [static_dataset.path](https://github.com/eloialonso/diamond/blob/312a0c4ef386bc031b8bdc1f2928100e7a2ef482/config/trainer.yaml#L50) argument of the configuration file. This should be a folder with two subfolders, `train` and `test`, each formatted as a `Dataset` from the [dataset.py](https://github.com/eloialonso/diamond/blob/main/src/data/dataset.py) file.

Do you have an example of the data set format?

**Comment by AdamJelley** [comment]
The CSGO data can be used as an example. You can see the creation of the low res dataset from the high res dataset in [process_csgo_tar_files.py](https://github.com/eloialonso/diamond/blob/csgo/src/process_csgo_tar_files.py#L111) for example.

**Comment by PeiPeiWow** [comment]
> The CSGO data can be used as an example. You can see the creation of the low res dataset from the high res dataset in [process_csgo_tar_files.py](https://github.com/eloialonso/diamond/blob/csgo/src/process_csgo_tar_files.py#L111) for example.

CSGO data can not be downloaded. Do you have any other url link to get the datasets?

**Comment by nathanvogel** [comment]
Thank you for the insights @AdamJelley (and great paper!). The CSGO dataset is currently unavailable [as per its own author](https://github.com/TeaPearce/Counter-Strike_Behavioural_Cloning/issues/25#issuecomment-2426609345). Would someone here be able to upload a sample of the low res training dataset?

It would help a lot with creating a custom dataset, as it's otherwise quite error prone.

**UPDATE:** Solved! ✅ The dataset [is being uploaded](https://github.com/TeaPearce/Counter-Strike_Behavioural_Cloning/issues/25#issuecomment-2428475660) to HuggingFace :)
