### ISSUE TITLE
can you provide the code？

### ISSUE THREAD

**Issue by ZhikanggFu** [eloialonso/diamond#2]
can you provide the code of calculate [results/data/DIAMOND.json](https://github.com/eloialonso/diamond/blob/main/results/data/DIAMOND.json)

**Comment by AdamJelley** [comment]
Each value in the results json corresponds to the final evaluation of a single training run (see [Launching a training run](https://github.com/eloialonso/diamond?tab=readme-ov-file#%EF%B8%8F-launch-a-training-run) in the README). The evaluation code can be found in `collect_test` (specifically, the value used is the `final_return_mean` on line 298), which is called at the end of `run`,  both in [src/trainer.py](https://github.com/eloialonso/diamond/blob/main/src/trainer.py). Hope that helps!
