### ISSUE TITLE
Can't train with "python src/main.py env.train.id=BreakoutNoFrameskip-v4 common.device=cuda:0"

### ISSUE THREAD

**Issue by 1846333564** [eloialonso/diamond#20]
I can have fun with"python src/play.py --pretrained".But I can not use "python src/main.py env.train.id=BreakoutNoFrameskip-v4 common.device=cuda:"to train.

`PS C:\Users\Leon\Desktop\diamond-main> set HYDRA_FULL_ERROR=1
PS C:\Users\Leon\Desktop\diamond-main> python src/main.py env.train.id=BreakoutNoFrameskip-v4 common.device=cuda:0
Could not override 'common.device'.
To append to your config use +common.device=cuda:0
Key 'device' is not in struct
    full_key: common.device
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.`

and I also can't use 

`PS C:\Users\Leon\Desktop\diamond-main> python src/main.py env.train.id=BreakoutNoFrameskip-v4 +common.device=cuda:0
Starting on cpu:0
A.L.E: Arcade Learning Environment (version 0.8.1+53f58b7)
[Powered by Stella]
A.L.E: Arcade Learning Environment (version 0.8.1+53f58b7)
[Powered by Stella]
A.L.E: Arcade Learning Environment (version 0.8.1+53f58b7)
[Powered by Stella]`

CPU is Extreme slow.

I didn't change any code or yaml. 

Thank you very much for your code.

**Comment by AdamJelley** [comment]
Hi, thanks for the issue! 

There's indeed a discrepancy between the readme and the latest code. You need to use `common.devices=0` rather than `common.device=cuda:0`. 

We'll update the readme accordingly - thanks for letting us know!

**Comment by 1846333564** [comment]
thank you very much!
