### ISSUE TITLE
Discord, reddit, or community engagement

### ISSUE THREAD

**Issue by sl33pyC01E** [eloialonso/diamond#28]
Hello, 
this is a fantastic project.

The fact that it can be trained and ran on a 4090 is very exciting to a lot of people, myself included. 

Is there any plans on making a discord, subreddit, or any other community space to facilitate local experimentation?

If we could get a forum going, I imagine a significant amount of trial and error can be completed by 'us', but the information provided in this repository in regard to training is seemingly sparse.

I think to garner popularity, the open sourced version of flappy bird would be a good target as it does not require icons, text, meters, or enemies, and the entire game loop is both constantly in predictable motion and visually apparent at all times. The single user input is also nice. 
I would like to attempt to train or assist in training this, but am unsure how to start, and figure there are a lot of others in the same boat.

If we had a forum to share our progress with some creator oversight/insight, I think more progress can be made.

**Comment by eloialonso** [comment]
Hi @sl33pyC01E, thanks for the kind words.

We think a discord server is a great idea, thanks for the suggestion! --> https://discord.gg/74vha5RWPg
