### ISSUE TITLE
Can you provide the code for training the diffusion model

### ISSUE THREAD

**Issue by SliencerX** [eloialonso/diamond#3]
Dear authors,

Thanks for sharing the code! I did not find the code to train the diffusion model. Could you upload those code? Thanks!

Sincerely

**Comment by eloialonso** [comment]
Hello @SliencerX! 

The code is already available in this repository (in the [src](https://github.com/eloialonso/diamond/tree/main/src) folder).
Please refer to the [Launch a training run](https://github.com/eloialonso/diamond?tab=readme-ov-file#%EF%B8%8F-launch-a-training-run) section of the README for instructions on how to launch a training run.

Also, you can find the diffusion-specific code in [src/models/diffusion](https://github.com/eloialonso/diamond/blob/main/src/models/diffusion).

Hope this helps!

**Comment by SliencerX** [comment]
Hi,

Thanks for the quick replay!. I noticed that in the paper you also implement a DDPM based diffusion. Could you also provide the code for the DDPM version of the diffusion model?

Sincerely
