### ISSUE TITLE
Great job, but How can I load this with vscode remote? 

### ISSUE THREAD

**Issue by yanghu819** [eloialonso/diamond#31]

**Comment by eloialonso** [comment]
Thanks for the kind words. Closing as this is not an issue with our code. We suggest you look for online tutorials for this kind of issue.

**Comment by xizaoqu** [comment]
Hi, I actually have the same problem. I do not have a local machine that can run the code. It would be good if there is a way I can run it headless.

**Comment by CS-GangXu** [comment]
hi, you can ensure the X11Forwarding yes in your 'sshd_config', and then `sudo apt install xauth', 'sudo apt install x11-app'

Install `VcXsrV' On windows.
Set the system environment variable of your windows 'DISPLAY' to be 'localhost:0.0'.
Open 'XLaunch',  set the display number to be 0, set “Disable access control”.

Open a terminal in remote server, 'export DISPLAY=Your Windows IP:0.0'.

Then, try 'xeyes', if you see eyes in your windwos. That's OK.

Finally, you should set the 'env' in vscode: 'export DISPLAY=Your Windows IP:0.0' to run the code.
