### ISSUE TITLE
Regarding questions about Atari Freeway

### ISSUE THREAD

**Issue by LJH-coding** [eloialonso/diamond#34]
Hi, may I ask if DIAMOND used the same trick as IRIS when training Freeway, specifically lowering the temperature? I noticed that when I trained Freeway using the default config, its return was always 0. Since the DIAMOND paper doesn't explicitly mention this point, I wanted to confirm with you.

**Comment by AdamJelley** [comment]
Hi, yes, DIAMOND's RL pipeline is based on [IRIS](https://arxiv.org/pdf/2209.00588) and uses the same trick explained in Appendix H of that paper. Thanks for pointing that out!
