### ISSUE TITLE
Training model using multiple GPUs

### ISSUE THREAD

**Issue by KaiLiu18** [eloialonso/diamond#35]
Thank you for your excellent work! I am attempting to train a model on my custom dataset using multiple GPUs. However, I have encountered an issue: `RuntimeError: No backend type associated with device type cpu`. This error does not occur when I train the model using a single GPU. Therefore, I am unsure if I have overlooked something or how I can resolve this problem.

**Comment by eloialonso** [comment]
Thanks for the kind words! 

Indeed, we did not realize the last commit to reduce memory usage was breaking the multi gpu. 
Should be fixed with the latest commit (851cefb) now.

Can you confirm?

**Comment by KaiLiu18** [comment]
Thank you very much for your prompt response and fix! I have pulled the latest commit and tested it. I'm happy to report that the multi-GPU functionality is now working correctly, and the memory usage has been optimized as well.
