### ISSUE TITLE
Details fading out as diffusion model training goes on

### ISSUE THREAD

**Issue by SliencerX** [eloialonso/diamond#4]
Hi,

I met some problems with the diffusion model training. For my project I resize the game frame to gray scale with size 84*84. 
![Early training reconstruct](https://github.com/user-attachments/assets/162c6df6-d7c2-44a3-bb61-7a99bbb764fa) This is the reconstruction during early stage training. 
![att230](https://github.com/user-attachments/assets/dd3d5f57-7137-4379-b718-cbfdb9f84b73) And this is the reconstruction result as training goes on, where the details on the image are fading out. 

Could you give me some advice on this problem?

Sincerely.

**Comment by AdamJelley** [comment]
Hi @SliencerX,

It's difficult to assess what might be going wrong without access to your training logs and project code. Images fading out could be an issue with data normalization, so we'd suggest checking your data and pre-processing. We hope you manage to find the problem and please don't hesitate to re-open the issue if you think there might be a bug with our code.

Hope that helps and good luck!

**Comment by SliencerX** [comment]
Fixed by finding a bug in my sampling code.
