### ISSUE TITLE
Error when loading checkpoint on torch 2.0.1 + mps

### ISSUE THREAD

**Issue by jsrgb** [eloialonso/diamond#6]
`PYTORCH_ENABLE_MPS_FALLBACK=1 python src/play.py` on the csgo branch, m1 mac:

`RuntimeError: don't know how to restore data location of torch.storage.UntypedStorage (tagged with mps:0)`

Works after upgrading to torch==2.4.1

**Comment by eloialonso** [comment]
Good catch, thank you! We upgraded the requirements :)
