### ISSUE TITLE
Question about training

### ISSUE THREAD

**Issue by alhojel** [eloialonso/diamond#7]
Thanks! This is very very cool.

Are there any resources on how the model was trained? Particularly detailing the differences between the previous architecture used for DOOM and the benefits in speed that came from them?

Again, thanks.

**Comment by TheMindExpansionNetwork** [comment]
Yeah I'm with you on this like how would hard it be to train just a digital world

Lets say you make it unreal record collect data then make into this diffusion magic for endless generations

**Comment by eloialonso** [comment]
Hey @alhojel, thanks for the kind words!

GameNGen (DOOM) was not by us, you can compare [their paper](https://arxiv.org/pdf/2408.14837) with [ours](https://arxiv.org/pdf/2405.12399) to get differences.

As for our training, we describe [in the README](https://github.com/eloialonso/diamond/tree/csgo?tab=readme-ov-file#data) the data we used, and the provided code is the code we used to train, with this exact configuration. You can run it with `python src/main.py`, provided that you have the data downloaded on your machine.
