### ISSUE TITLE
Packages issue

### ISSUE THREAD

**Issue by f1amy** [eloialonso/diamond#8]
```
ERROR: Cannot install shimmy[atari]==0.1.0, shimmy[atari]==0.2.0 and shimmy[atari]==0.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    shimmy[atari] 0.2.1 depends on ale-py~=0.8.1; extra == "atari"
    shimmy[atari] 0.2.0 depends on ale-py~=0.8.0; extra == "atari"
    shimmy[atari] 0.1.0 depends on ale-py~=0.8.0; extra == "atari"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by l33tm4st3r** [comment]
remove ==0.1.0 from requeriments 

shimmy[atari]==0.1.0  <------before

shimmy[atari] <--------- after

**Comment by f1amy** [comment]
`requirements.txt` do not have this dependency

```
$ cat requirements.txt
gymnasium[atari,accept-rom-license]==0.29.1
h5py==3.11.0
huggingface-hub==0.17.2
hydra-core==1.3
numpy==1.26.0
opencv-python==4.8.0.76
pillow==10.3.0
pygame==2.5.2
torch==2.4.1
torcheval==0.0.7
tqdm==4.66.4
wandb==0.17.0
```

**Comment by f1amy** [comment]
this seems like an issue of a sub-dependecy that is used

one thing to note is that I'm using 3.12
```
$ python3 --version
Python 3.12.4
```

I haven't seen python version requirement in the readme

**Comment by Zenchiyu** [comment]
Hello,

The Python version we used in the demo was 3.10.12 (but it also works on my machine with Python 3.12.3 and an old GTX 1070, even though it's super slow)

Can you try replacing `gymnasium[atari,accept-rom-license]==0.29.1` with `gymnasium==0.29.1` (for the CS:GO world model) ?

**Comment by f1amy** [comment]
This did work for the `csgo` branch, thanks
```
$ cat requirements.txt
gymnasium==0.29.1
h5py==3.11.0
huggingface-hub==0.17.2
hydra-core==1.3
numpy==1.26.0
opencv-python==4.8.0.76
pillow==10.3.0
pygame==2.5.2
torch==2.4.1
torcheval==0.0.7
tqdm==4.66.4
wandb==0.17.0
```

**Comment by mezotaken** [comment]
Can confirm, it works for csgo branch

**Comment by AdamJelley** [comment]
Indeed if you really want to use `python 3.12` for CSGO, then you can just replace the `gymnasium[atari,accept-rom-license]==0.29.1` dependency with `gymnasium==0.29.1`. However, this will break the `main` branch for Atari, which requires the additional dependencies.

Therefore, we recommend keeping the requirements as they are and using `python 3.10` as suggested in the [README](https://github.com/eloialonso/diamond) so you do not get this dependency conflict at all, which enables you to also run the `main` branch for Atari as well.

**Comment by EntityinArray** [comment]
> Hello,
> 
> The Python version we used in the demo was 3.10.12 (but it also works on my machine with Python 3.12.3 and an old GTX 1070, even though it's super slow)
> 
> Can you try replacing `gymnasium[atari,accept-rom-license]==0.29.1` with `gymnasium==0.29.1` (for the CS:GO world model) ?

would it be possible to push this change to repo?
