### ISSUE TITLE
How can I enable GPU?

### ISSUE THREAD

**Issue by Crimsonfart** [eloialonso/diamond#9]
Everything works but it is extremely slow because it only runs on the CPU. Where can I activate GPU 0? (4090)

**Comment by BilllliBbob** [comment]
I am in the same boat, I have a 4090, but it is choosing my Threadripper CPU

**Comment by Zenchiyu** [comment]
Hello,

If you call `torch.cuda.is_available()` after importing torch, does it return True?

**Comment by dk000000000** [comment]
> Hello,
> 
> If you call `torch.cuda.is_available()` after importing torch, does it return True?

it returns false, it seem install requirement does not include cuda

**Comment by Zenchiyu** [comment]
Hm interesting, mine returns True. 

Did you activate the environment with `source ./diamond_env/bin/activate` ?
Or could you please try to reinstall PyTorch with this https://pytorch.org/get-started/locally/ ?

**Comment by eloialonso** [comment]
Do you have the Nvidia drivers installed?

**Comment by dk000000000** [comment]
> Hm interesting, mine returns True.
> 
> Did you activate the environment with `source ./diamond_env/bin/activate` ? Or could you please try to reinstall PyTorch with this https://pytorch.org/get-started/locally/ ?

yes, env is activated and nvidia drivers are installed
i am still downloading cuda through conda pytorch install
guess new conda env can't find other cuda pytorch i installed in different env

**Comment by Crimsonfart** [comment]
OK, after `conda activate diamond` i ran `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118` and after that it worked. Thanks for the quick help and the great project. Unfortunately it loses focus very quickly if you walk or look away from the standard path, but it's still fascinating and cool! THANK YOU for your efforts.

**Comment by dk000000000** [comment]
now it works, but windows installation it seem need to add 
`import torch._dynamo
torch._dynamo.config.suppress_errors = True`
to get around triton

Also i find it will mode collapse when you shot at the wall, and turn to the right, the no matter what you do you only see is sand color.
i run with python src/play.py --compile
with csgo branch

**Comment by dk000000000** [comment]
man, this thing mode collapse so fast, 
you face a near pure color wall, you spin, all you see is this wall color.

**Comment by Zenchiyu** [comment]
It doesn't have much memory, the generation is only based on a few past frames (like 3 for instance)

**Comment by dk000000000** [comment]
> It doesn't have much memory, the generation is only based on a few past frames (like 3 for instance)

i see, the config default set to 4, i will increase see if it helped

**Comment by eloialonso** [comment]
You cannot increase it like that, you would have to retrain the model :)

**Comment by dk000000000** [comment]
> You cannot increase it like that, you would have to retrain the model :)
true, increased to 20 still the same

**Comment by eloialonso** [comment]
@dk000000000 fyi, changing it to 20 has no effect since we overwrite the `agent` part of the config with the config that corresponds to the model.

In details, we download [this file](https://huggingface.co/eloialonso/diamond/blob/main/csgo/config/agent/csgo.yaml) from the hugging face hub. This happens in [src/play.py#L45](https://github.com/eloialonso/diamond/blob/dd4788aaa82c7d6415e1f1a6cb7af4d6dbe2f97b/src/play.py#L45).

(Same thing with the `env` part of the config on the next line)

**Comment by GostaFPS** [comment]
hey im a noobie on these things i just wanna get it running on my gpu through the powershell terminal but i cant get it to work on the gpu its only running on the cpu.

any tips would help  <3

**Comment by eloialonso** [comment]
Hey, thanks for the interest :) 

You have to make sure that you have a cuda-enabled installation of PyTorch (in a Python shell, `import torch; torch.cuda.is_available()` should return `True`). You can try installing from [the official PyTorch website](https://pytorch.org/get-started/locally/), with the right OS and version of CUDA (provided that you have an Nvidia GPU).

**Comment by GostaFPS** [comment]
> Hey, thanks for the interest :)
> 
> You have to make sure that you have a cuda-enabled installation of PyTorch (in a Python shell, `import torch; torch.cuda.is_available()` should return `True`). You can try installing from [the official PyTorch website](https://pytorch.org/get-started/locally/), with the right OS and version of CUDA (provided that you have an Nvidia GPU).

yea i just still dont know how to run this kind of code through python shell if you dont mine giving me a run down because im trying to run it on the windows powershell atm and i know absolutely nothing about python at all.

sorry if im a bother to you but this kind of thing is intersting and i wanna get in to it a bit more and i just dont really know what to do with this i want something that i can drop in anaconda or powershell and lets me run it on my gpu.

sorry again and thank you

**Comment by AdamJelley** [comment]
On Windows, you'd be best to use [wsl](https://learn.microsoft.com/en-us/windows/wsl/). You can [install it](https://learn.microsoft.com/en-us/windows/wsl/install#install-wsl-command) by opening PowerShell **in administrator mode** by right-clicking on it and selecting "Run as administrator", entering the command `wsl --install`, then restarting your machine.

Then you can open PowerShell again, and run wsl by entering `wsl`. Once in wsl, you'll need to install Miniconda by following the instructions [here](https://docs.anaconda.com/miniconda/#quick-command-line-install) (**for Linux**). You can then just copy the [installation instructions](https://github.com/eloialonso/diamond/tree/csgo?tab=readme-ov-file#installation) from our README and it should run.

Hope that helps!
